package br.com.manicure.gui.cliente;

import br.com.manicure.dao.factory.DAOFactory;
import br.com.manicure.gui.FixedButtonModel;
import br.com.manicure.gui.agendamento.EditarAgendamento;
import br.com.manicure.model.Cliente;
import br.com.manicure.tabelas.ClienteTable;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author John
 */
public class ClienteEditar extends javax.swing.JFrame {

    private final EditarAgendamento agenda;
    private final ClienteTable tableModelClientes = new ClienteTable();

    /**
     * Creates new form ClienteBuscar
     *
     * @param e
     */
    public ClienteEditar(EditarAgendamento e) {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/br/com/manicure/icones/clientesicon.png")).getImage());
        bOkCliente.setModel(new FixedButtonModel());
        bOkCliente.setBorder(BorderFactory.createEtchedBorder(0));
        bCancelarCliente.setModel(new FixedButtonModel());
        bCancelarCliente.setBorder(BorderFactory.createEtchedBorder(0));
        scrollPanelPaciente.getViewport().setBackground(Color.WHITE);
        scrollPanelPaciente.setBorder(BorderFactory.createEmptyBorder());
        tableClientes.setShowVerticalLines(false);
        List<Cliente> lista = DAOFactory.getClienteDAO().listar();
        if (lista != null) {
            tableModelClientes.addLista(lista);
        }
        tableClientes.setModel(tableModelClientes);
        UIDefaults defaults = UIManager.getLookAndFeelDefaults();
        defaults.put("Button.focus", new ColorUIResource(new Color(0, 0, 0, 0)));
        this.agenda = e;
        this.setTitle("Buscar Cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input = new javax.swing.JPanel();
        lPesquisar = new javax.swing.JLabel();
        tBuscarCliente = new javax.swing.JTextField();
        bOkCliente = new javax.swing.JButton();
        bCancelarCliente = new javax.swing.JButton();
        mainPaciente = new javax.swing.JPanel();
        scrollPanelPaciente = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(619, 264));

        input.setBackground(new java.awt.Color(247, 247, 247));

        lPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lPesquisar.setText("Pesquisar");
        lPesquisar.setMaximumSize(new java.awt.Dimension(40, 20));
        lPesquisar.setMinimumSize(new java.awt.Dimension(40, 20));
        lPesquisar.setPreferredSize(new java.awt.Dimension(40, 20));

        tBuscarCliente.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tBuscarClienteCaretUpdate(evt);
            }
        });

        bOkCliente.setBackground(new java.awt.Color(0, 102, 52));
        bOkCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bOkCliente.setForeground(new java.awt.Color(255, 255, 255));
        bOkCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/manicure/icones/Ok.png"))); // NOI18N
        bOkCliente.setText("Ok");
        bOkCliente.setBorder(null);
        bOkCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bOkCliente.setDoubleBuffered(true);
        bOkCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bOkClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bOkClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bOkClienteMouseExited(evt);
            }
        });

        bCancelarCliente.setBackground(new java.awt.Color(211, 0, 0));
        bCancelarCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bCancelarCliente.setForeground(new java.awt.Color(255, 255, 255));
        bCancelarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/manicure/icones/cancelar.png"))); // NOI18N
        bCancelarCliente.setText("Cancelar");
        bCancelarCliente.setBorder(null);
        bCancelarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bCancelarCliente.setDoubleBuffered(true);
        bCancelarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCancelarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCancelarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCancelarClienteMouseExited(evt);
            }
        });

        mainPaciente.setLayout(new java.awt.CardLayout());

        scrollPanelPaciente.setBorder(null);

        tableClientes.setAutoCreateRowSorter(true);
        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableClientes.setDoubleBuffered(true);
        scrollPanelPaciente.setViewportView(tableClientes);

        mainPaciente.add(scrollPanelPaciente, "card2");

        javax.swing.GroupLayout inputLayout = new javax.swing.GroupLayout(input);
        input.setLayout(inputLayout);
        inputLayout.setHorizontalGroup(
            inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addGroup(inputLayout.createSequentialGroup()
                        .addComponent(lPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tBuscarCliente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bOkCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        inputLayout.setVerticalGroup(
            inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mainPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOkCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOkClienteMouseEntered
        bOkCliente.setBackground(Color.decode("#008542"));
    }//GEN-LAST:event_bOkClienteMouseEntered

    private void bOkClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOkClienteMouseExited
        bOkCliente.setBackground(Color.decode("#006634"));
    }//GEN-LAST:event_bOkClienteMouseExited

    private void bCancelarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarClienteMouseClicked
        this.dispose();
    }//GEN-LAST:event_bCancelarClienteMouseClicked

    private void bCancelarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarClienteMouseEntered
        bCancelarCliente.setBackground(Color.decode("#AD0000"));
    }//GEN-LAST:event_bCancelarClienteMouseEntered

    private void bCancelarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarClienteMouseExited
        bCancelarCliente.setBackground(Color.decode("#D30000"));
    }//GEN-LAST:event_bCancelarClienteMouseExited

    private void bOkClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOkClienteMouseClicked
        int row = this.tableClientes.getSelectedRow();
        if (row > -1) {
            Cliente c = this.tableModelClientes.getCliente(row);
            this.agenda.setCliente(c);

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um(a) cliente da tabela", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bOkClienteMouseClicked

    private void tBuscarClienteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tBuscarClienteCaretUpdate
        searchCliente();
    }//GEN-LAST:event_tBuscarClienteCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
 /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteEditar().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelarCliente;
    private javax.swing.JButton bOkCliente;
    private javax.swing.JPanel input;
    private javax.swing.JLabel lPesquisar;
    private javax.swing.JPanel mainPaciente;
    private javax.swing.JScrollPane scrollPanelPaciente;
    private javax.swing.JTextField tBuscarCliente;
    private javax.swing.JTable tableClientes;
    // End of variables declaration//GEN-END:variables

    private void searchCliente() {
        String busca = this.tBuscarCliente.getText();
        List<Cliente> lista;
        lista = DAOFactory.getClienteDAO().filtrar(busca);
        if (lista != null) {
            this.tableModelClientes.addLista(lista);
        }
        this.tBuscarCliente.requestFocusInWindow();

    }

}
