package br.com.manicure.gui.cliente;

import br.com.manicure.dao.factory.DAOFactory;
import br.com.manicure.gui.Agenda;
import br.com.manicure.gui.pacote.BuscarPacotes;
import br.com.manicure.model.Cliente;
import br.com.manicure.model.Contato;
import br.com.manicure.model.Endereco;
import br.com.manicure.model.Formatacao;
import br.com.manicure.model.Pacotes;
import br.com.manicure.model.Validacao;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author John
 */
public class NovoCliente extends javax.swing.JFrame {

    private final Agenda tela;
    private Cliente cliente = null;
    private Pacotes pacote = null;

    /**
     * Creates new form NovoCliente
     *
     * @param tela
     */
    public NovoCliente(Agenda tela) {
        initComponents();
        this.tela = tela;
        this.setIconImage(new ImageIcon(getClass().getResource("/br/com/manicure/icones/clientesicon.png")).getImage());
        this.setTitle("Novo Cliente");
        tObservacao.setLineWrap(true);
        tObservacao.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        input = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tCPF = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tRG = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tDataNasc = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tRua = new javax.swing.JFormattedTextField();
        tNumero = new javax.swing.JTextField();
        tBairro = new javax.swing.JFormattedTextField();
        tCidade = new javax.swing.JFormattedTextField();
        tEstado = new javax.swing.JTextField();
        tCelular = new javax.swing.JFormattedTextField();
        tEmail = new javax.swing.JTextField();
        tCEP = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        boxSexo = new javax.swing.JComboBox<>();
        sObservacao = new javax.swing.JScrollPane();
        tObservacao = new javax.swing.JTextArea();
        bCancelarCliente = new javax.swing.JButton();
        bSalvarCliente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbSim = new javax.swing.JRadioButton();
        rbNao = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        input.setBackground(new java.awt.Color(247, 247, 247));
        input.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(211, 0, 0));
        jLabel5.setText("*");
        jLabel5.setMaximumSize(new java.awt.Dimension(5, 20));
        jLabel5.setMinimumSize(new java.awt.Dimension(5, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(5, 20));
        input.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 11, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setText("Nome");
        jLabel1.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        input.add(tNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 630, 29));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("CPF");
        jLabel4.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 34, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(211, 0, 0));
        jLabel8.setText("*");
        jLabel8.setMaximumSize(new java.awt.Dimension(5, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(5, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(5, 20));
        input.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 11, -1));

        try {
            tCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input.add(tCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, 28));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setText("RG");
        jLabel9.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 20, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(211, 0, 0));
        jLabel10.setText("*");
        jLabel10.setMaximumSize(new java.awt.Dimension(5, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(5, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(5, 20));
        input.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 7, -1));
        input.add(tRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 130, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Cel");
        jLabel6.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel6.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 24, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel11.setText("E-mail");
        jLabel11.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel11.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel11.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 48, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel14.setText("Observação");
        jLabel14.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel14.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel14.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 73, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel15.setText("Data de Nascimento");
        jLabel15.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel15.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel15.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 128, -1));

        try {
            tDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input.add(tDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 100, 28));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel17.setText("CEP");
        jLabel17.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel17.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel17.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 32, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel18.setText("Rua");
        jLabel18.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel18.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel18.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 28, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel19.setText("Número");
        jLabel19.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel19.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel19.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 56, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel20.setText("Bairro");
        jLabel20.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel20.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel20.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel21.setText("Cidade");
        jLabel21.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel21.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel21.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 48, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel22.setText("Estado");
        jLabel22.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel22.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel22.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 50, -1));
        input.add(tRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 402, 28));
        input.add(tNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 100, 28));
        input.add(tBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 210, 28));
        input.add(tCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 210, 28));
        input.add(tEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 100, 28));

        try {
            tCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input.add(tCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, 28));
        input.add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 211, 28));

        try {
            tCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input.add(tCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 130, 28));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel23.setText("Sexo");
        jLabel23.setMaximumSize(new java.awt.Dimension(40, 20));
        jLabel23.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel23.setPreferredSize(new java.awt.Dimension(40, 20));
        input.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        boxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                       ", "Masculino", "Feminino" }));
        input.add(boxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 126, 26));

        tObservacao.setColumns(20);
        tObservacao.setRows(5);
        sObservacao.setViewportView(tObservacao);

        input.add(sObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 351, 160));

        bCancelarCliente.setBackground(new java.awt.Color(183, 21, 1));
        bCancelarCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bCancelarCliente.setForeground(new java.awt.Color(255, 255, 255));
        bCancelarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/manicure/icones/cancelar.png"))); // NOI18N
        bCancelarCliente.setText("Cancelar");
        bCancelarCliente.setBorder(null);
        bCancelarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bCancelarCliente.setDoubleBuffered(true);
        bCancelarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCancelarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCancelarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCancelarClienteMouseExited(evt);
            }
        });
        input.add(bCancelarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 110, 40));

        bSalvarCliente.setBackground(new java.awt.Color(0, 102, 52));
        bSalvarCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bSalvarCliente.setForeground(new java.awt.Color(255, 255, 255));
        bSalvarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/manicure/icones/Ok.png"))); // NOI18N
        bSalvarCliente.setText("Salvar");
        bSalvarCliente.setBorder(null);
        bSalvarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bSalvarCliente.setDoubleBuffered(true);
        bSalvarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalvarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSalvarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSalvarClienteMouseExited(evt);
            }
        });
        input.add(bSalvarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 104, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(211, 0, 0));
        jLabel12.setText("*");
        jLabel12.setMaximumSize(new java.awt.Dimension(5, 20));
        jLabel12.setMinimumSize(new java.awt.Dimension(5, 20));
        jLabel12.setPreferredSize(new java.awt.Dimension(5, 20));
        input.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 11, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(211, 0, 0));
        jLabel13.setText("*");
        jLabel13.setMaximumSize(new java.awt.Dimension(5, 20));
        jLabel13.setMinimumSize(new java.awt.Dimension(5, 20));
        jLabel13.setPreferredSize(new java.awt.Dimension(5, 20));
        input.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 10, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Pacote ");
        input.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 48, -1));

        rbSim.setBackground(new java.awt.Color(247, 247, 247));
        buttonGroup1.add(rbSim);
        rbSim.setText("Sim");
        rbSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSimActionPerformed(evt);
            }
        });
        input.add(rbSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        rbNao.setBackground(new java.awt.Color(247, 247, 247));
        buttonGroup1.add(rbNao);
        rbNao.setText("Não");
        rbNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNaoActionPerformed(evt);
            }
        });
        input.add(rbNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarClienteMouseClicked
        this.dispose();
    }//GEN-LAST:event_bCancelarClienteMouseClicked

    private void bCancelarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarClienteMouseEntered
        bCancelarCliente.setBackground(Color.decode("#AD0000"));
    }//GEN-LAST:event_bCancelarClienteMouseEntered

    private void bCancelarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarClienteMouseExited
        bCancelarCliente.setBackground(Color.decode("#D30000"));
    }//GEN-LAST:event_bCancelarClienteMouseExited

    private void bSalvarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalvarClienteMouseEntered
        bSalvarCliente.setBackground(Color.decode("#008542"));
    }//GEN-LAST:event_bSalvarClienteMouseEntered

    private void bSalvarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalvarClienteMouseExited
        bSalvarCliente.setBackground(Color.decode("#006634"));
    }//GEN-LAST:event_bSalvarClienteMouseExited

    private void rbSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSimActionPerformed
        BuscarPacotes pacotes = new BuscarPacotes(this);
        if (rbSim.isSelected()) {
            pacotes.setVisible(true);
        }
    }//GEN-LAST:event_rbSimActionPerformed

    private void rbNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNaoActionPerformed
        BuscarPacotes pacotes = new BuscarPacotes(this);
        if (rbNao.isSelected()) {
            pacotes.setVisible(false);
        }

    }//GEN-LAST:event_rbNaoActionPerformed

    private void bSalvarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalvarClienteMouseClicked
        String CPF = Formatacao.removeCPFmask(tCPF.getText());
        String RG = Formatacao.removeRGmask(tRG.getText());
        String CELULAR = Formatacao.removeFoneMask(tCelular.getText());
        String SEXO = boxSexo.getItemAt(boxSexo.getSelectedIndex());

        if (Validacao.isEmpty(CPF) || Validacao.isEmpty(tNome.getText()) || Validacao.isEmpty(CELULAR) || Validacao.isEmpty(tRua.getText()) || Validacao.isEmpty(tNumero.getText())) {
            JOptionPane.showMessageDialog(null, "Os campos (Nome), (CPF), (Celular), (Rua) e (Numero) são obrigatórios", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!Validacao.CPFisValid(CPF)) {
            JOptionPane.showMessageDialog(null, "CPF inválido", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (Validacao.CPFexists(CPF, 0)) {
            JOptionPane.showMessageDialog(null, "CPF já cadastrado", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!Validacao.hasOnlyLettersAndNumbers(RG)) {
            JOptionPane.showMessageDialog(null, "O campo (RG) deve conter apenas números, letras, pontos(.) ou traços (-)", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!Validacao.dateIsValid(tDataNasc.getText())) {
            JOptionPane.showMessageDialog(null, "Data inválida", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!Validacao.isEmpty(tNumero.getText()) && !Validacao.isNumeric(tNumero.getText())) {
            JOptionPane.showMessageDialog(null, "O campo (Número) deve conter apenas números", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!Validacao.isEmpty(tEstado.getText()) && !Validacao.equals(tEstado.getText(), 2)) {
            JOptionPane.showMessageDialog(null, "O campo (Estado) deve conter apenas 2 caracteres (SIGLA)", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String CEP = Formatacao.removeCEPmask(tCEP.getText());
        Cliente c = new Cliente();
        Endereco e = new Endereco();
        Contato co = new Contato();
        Pacotes p = null;

        e.setCep(CEP);
        e.setRua(tRua.getText());
        e.setNumero(Integer.parseInt(tNumero.getText()));
        e.setBairro(tBairro.getText());
        e.setCidade(tCidade.getText());
        e.setEstado(tEstado.getText());

        co.setCelular(tCelular.getText());
        co.setEmail(tEmail.getText());

        if (rbSim.isSelected()) {
            p = new Pacotes();
            p.setIdPacote(pacote.getIdPacote());
            p.setNome(pacote.getNome());
            p.setValor(pacote.getValor());
            p.setDescricao(pacote.getDescricao());

        }

        c.setNome(tNome.getText());
        c.setCpf(CPF);
        c.setRg(RG);
        c.setDataNasc(Formatacao.string2Date(tDataNasc.getText()));
        c.setEndereco(e);
        c.setContato(co);
        c.setPacote(p);
        c.setSexo(SEXO);
        c.setObservacao(tObservacao.getText());

        DAOFactory.getClienteDAO().cadastrar(c);
        JOptionPane.showMessageDialog(null, "O Cadastro foi efetuado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        List<Cliente> lista = DAOFactory.getClienteDAO().listar();
        if (lista != null) {
            this.tela.tableModelClientes.addLista(lista);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao realizar o cadastro. Tente novamente mais tarde ou contate o Administrador do sistema", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bSalvarClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoCliente().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelarCliente;
    private javax.swing.JButton bSalvarCliente;
    private javax.swing.JComboBox<String> boxSexo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbNao;
    private javax.swing.JRadioButton rbSim;
    private javax.swing.JScrollPane sObservacao;
    private javax.swing.JFormattedTextField tBairro;
    private javax.swing.JFormattedTextField tCEP;
    private javax.swing.JFormattedTextField tCPF;
    private javax.swing.JFormattedTextField tCelular;
    private javax.swing.JFormattedTextField tCidade;
    private javax.swing.JFormattedTextField tDataNasc;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tEstado;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tNumero;
    private javax.swing.JTextArea tObservacao;
    private javax.swing.JFormattedTextField tRG;
    private javax.swing.JFormattedTextField tRua;
    // End of variables declaration//GEN-END:variables

    public void setPacote(Pacotes p) {
        this.pacote = p;
    }

    public Pacotes getPacote() {
        return this.pacote;
    }
}
