package br.com.manicure.esmalte;

import br.com.manicure.DAO.EsmalteDAO;
import br.com.manicure.dao.factory.DAOFactory;
import br.com.manicure.gui.agendamento.NovoAgendamento;
import br.com.manicure.model.Esmalte;
import br.com.manicure.tabelas.EsmalteTable;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author Jhon
 */
public class BuscarEsmalte extends javax.swing.JFrame {

    EsmalteTable tableModelEsmalte = new EsmalteTable();
    EsmalteDAO eDAO = new EsmalteDAO();
    NovoAgendamento agenda = null;

    /**
     * Creates new form BuscarEsmalte
     *
     * @param a
     */
    public BuscarEsmalte(NovoAgendamento a) {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/br/com/manicure/icones/esmalteicon.png")).getImage());
        scrollPanelEsmalte.getViewport().setBackground(Color.WHITE);
        scrollPanelEsmalte.setBorder(BorderFactory.createEmptyBorder());
        tableEsmalte.setShowVerticalLines(false);
        UIManager.put("OptionPane.background", new ColorUIResource(255, 255, 255));
        UIManager.put("Panel.background", new ColorUIResource(255, 255, 255));
        UIManager.put("Button.background", Color.WHITE);
        List<Esmalte> lista = DAOFactory.getEsmalteDAO().listar();
        if (lista != null) {
            tableModelEsmalte.addLista(lista);
        }
        tableEsmalte.setModel(tableModelEsmalte);
        this.agenda = a;
        UIDefaults defaults = UIManager.getLookAndFeelDefaults();
        defaults.put("Button.focus", new ColorUIResource(new Color(0, 0, 0, 0)));
        this.setTitle("Buscar Esmalte");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input = new javax.swing.JPanel();
        lPesquisar = new javax.swing.JLabel();
        tBuscarEsmalte = new javax.swing.JTextField();
        bOkEsmalte = new javax.swing.JButton();
        bCancelarEsmalte = new javax.swing.JButton();
        mainCliente = new javax.swing.JPanel();
        scrollPanelEsmalte = new javax.swing.JScrollPane();
        tableEsmalte = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        input.setBackground(new java.awt.Color(247, 247, 247));

        lPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lPesquisar.setText("Pesquisar");
        lPesquisar.setMaximumSize(new java.awt.Dimension(40, 20));
        lPesquisar.setMinimumSize(new java.awt.Dimension(40, 20));
        lPesquisar.setPreferredSize(new java.awt.Dimension(40, 20));

        tBuscarEsmalte.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tBuscarEsmalteCaretUpdate(evt);
            }
        });

        bOkEsmalte.setBackground(new java.awt.Color(0, 102, 52));
        bOkEsmalte.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bOkEsmalte.setForeground(new java.awt.Color(255, 255, 255));
        bOkEsmalte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/manicure/icones/Ok.png"))); // NOI18N
        bOkEsmalte.setText("Ok");
        bOkEsmalte.setBorder(null);
        bOkEsmalte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bOkEsmalte.setDoubleBuffered(true);
        bOkEsmalte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bOkEsmalteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bOkEsmalteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bOkEsmalteMouseExited(evt);
            }
        });

        bCancelarEsmalte.setBackground(new java.awt.Color(211, 0, 0));
        bCancelarEsmalte.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bCancelarEsmalte.setForeground(new java.awt.Color(255, 255, 255));
        bCancelarEsmalte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/manicure/icones/cancelar.png"))); // NOI18N
        bCancelarEsmalte.setText("Cancelar");
        bCancelarEsmalte.setBorder(null);
        bCancelarEsmalte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bCancelarEsmalte.setDoubleBuffered(true);
        bCancelarEsmalte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCancelarEsmalteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCancelarEsmalteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCancelarEsmalteMouseExited(evt);
            }
        });

        mainCliente.setLayout(new java.awt.CardLayout());

        scrollPanelEsmalte.setBorder(null);

        tableEsmalte.setAutoCreateRowSorter(true);
        tableEsmalte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEsmalte.setDoubleBuffered(true);
        scrollPanelEsmalte.setViewportView(tableEsmalte);

        mainCliente.add(scrollPanelEsmalte, "card2");

        javax.swing.GroupLayout inputLayout = new javax.swing.GroupLayout(input);
        input.setLayout(inputLayout);
        inputLayout.setHorizontalGroup(
            inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addGroup(inputLayout.createSequentialGroup()
                        .addComponent(lPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tBuscarEsmalte))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bOkEsmalte, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelarEsmalte, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        inputLayout.setVerticalGroup(
            inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tBuscarEsmalte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mainCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOkEsmalte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelarEsmalte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkEsmalteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOkEsmalteMouseEntered
        bOkEsmalte.setBackground(Color.decode("#008542"));
    }//GEN-LAST:event_bOkEsmalteMouseEntered

    private void bOkEsmalteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOkEsmalteMouseExited
        bOkEsmalte.setBackground(Color.decode("#006634"));
    }//GEN-LAST:event_bOkEsmalteMouseExited

    private void bCancelarEsmalteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarEsmalteMouseClicked
        this.dispose();
    }//GEN-LAST:event_bCancelarEsmalteMouseClicked

    private void bCancelarEsmalteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarEsmalteMouseEntered
        bCancelarEsmalte.setBackground(Color.decode("#AD0000"));
    }//GEN-LAST:event_bCancelarEsmalteMouseEntered

    private void bCancelarEsmalteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarEsmalteMouseExited
        bCancelarEsmalte.setBackground(Color.decode("#D30000"));
    }//GEN-LAST:event_bCancelarEsmalteMouseExited

    private void bOkEsmalteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOkEsmalteMouseClicked
        int row = this.tableEsmalte.getSelectedRow();
        if (row > -1) {
            Esmalte e = this.tableModelEsmalte.getEsmalte(row); // variavel p recebe pacote da lista que foi selecionado
            this.agenda.setCorEsmalte(e);

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um esmalte da tabela", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bOkEsmalteMouseClicked

    private void tBuscarEsmalteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tBuscarEsmalteCaretUpdate
        searchEsmalte();
    }//GEN-LAST:event_tBuscarEsmalteCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarEsmalte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarEsmalte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarEsmalte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarEsmalte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarEsmalte().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelarEsmalte;
    private javax.swing.JButton bOkEsmalte;
    private javax.swing.JPanel input;
    private javax.swing.JLabel lPesquisar;
    private javax.swing.JPanel mainCliente;
    private javax.swing.JScrollPane scrollPanelEsmalte;
    private javax.swing.JTextField tBuscarEsmalte;
    private javax.swing.JTable tableEsmalte;
    // End of variables declaration//GEN-END:variables

    private void searchEsmalte() {
        String busca = this.tBuscarEsmalte.getText();
        List<Esmalte> lista;
        lista = DAOFactory.getEsmalteDAO().filtrar(busca);
        if (lista != null) {
            this.tableModelEsmalte.addLista(lista);
        }
        this.tBuscarEsmalte.requestFocusInWindow();

    }
}
